default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.10.0
    hooks:
      - id: commitizen
        additional_dependencies: [cz-conventional-gitmoji]

  - repo: https://github.com/ljnsn/cz-conventional-gitmoji
    rev: v0.7.0
    hooks:
      - id: conventional-gitmoji

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff check
        language: system
        stages:
          - commit
        files: \.(py|pyi)$
        args: [--fix]

      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format
        language: system
        stages:
          - commit
        files: \.(py|pyi)$

      - id: pyrefly
        name: pyrefly
        entry: uv run pyrefly check
        language: system
        pass_filenames: true
        stages:
          - commit
        files: \.(py|pyi)$

      - id: testing
        name: testing
        language: system
        entry: uv run pytest
        stages:
          - commit
        pass_filenames: false
        files: \.(py|pyi)$
